/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamplesRouteRouteImport } from './routes/_examples/route'
import { Route as ExamplesIndexRouteImport } from './routes/_examples/index'
import { Route as ExamplesSineEasingRouteImport } from './routes/_examples/sine-easing'
import { Route as ExamplesScrollTriggerRouteImport } from './routes/_examples/scroll-trigger'
import { Route as ExamplesPinningElementsRouteImport } from './routes/_examples/pinning-elements'
import { Route as ExamplesFirstAnimationRouteImport } from './routes/_examples/first-animation'
import { Route as ExamplesBackEasingRouteImport } from './routes/_examples/back-easing'

const ExamplesRouteRoute = ExamplesRouteRouteImport.update({
  id: '/_examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesRouteRoute,
} as any)
const ExamplesSineEasingRoute = ExamplesSineEasingRouteImport.update({
  id: '/sine-easing',
  path: '/sine-easing',
  getParentRoute: () => ExamplesRouteRoute,
} as any)
const ExamplesScrollTriggerRoute = ExamplesScrollTriggerRouteImport.update({
  id: '/scroll-trigger',
  path: '/scroll-trigger',
  getParentRoute: () => ExamplesRouteRoute,
} as any)
const ExamplesPinningElementsRoute = ExamplesPinningElementsRouteImport.update({
  id: '/pinning-elements',
  path: '/pinning-elements',
  getParentRoute: () => ExamplesRouteRoute,
} as any)
const ExamplesFirstAnimationRoute = ExamplesFirstAnimationRouteImport.update({
  id: '/first-animation',
  path: '/first-animation',
  getParentRoute: () => ExamplesRouteRoute,
} as any)
const ExamplesBackEasingRoute = ExamplesBackEasingRouteImport.update({
  id: '/back-easing',
  path: '/back-easing',
  getParentRoute: () => ExamplesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ExamplesIndexRoute
  '/back-easing': typeof ExamplesBackEasingRoute
  '/first-animation': typeof ExamplesFirstAnimationRoute
  '/pinning-elements': typeof ExamplesPinningElementsRoute
  '/scroll-trigger': typeof ExamplesScrollTriggerRoute
  '/sine-easing': typeof ExamplesSineEasingRoute
}
export interface FileRoutesByTo {
  '/back-easing': typeof ExamplesBackEasingRoute
  '/first-animation': typeof ExamplesFirstAnimationRoute
  '/pinning-elements': typeof ExamplesPinningElementsRoute
  '/scroll-trigger': typeof ExamplesScrollTriggerRoute
  '/sine-easing': typeof ExamplesSineEasingRoute
  '/': typeof ExamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_examples': typeof ExamplesRouteRouteWithChildren
  '/_examples/back-easing': typeof ExamplesBackEasingRoute
  '/_examples/first-animation': typeof ExamplesFirstAnimationRoute
  '/_examples/pinning-elements': typeof ExamplesPinningElementsRoute
  '/_examples/scroll-trigger': typeof ExamplesScrollTriggerRoute
  '/_examples/sine-easing': typeof ExamplesSineEasingRoute
  '/_examples/': typeof ExamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/back-easing'
    | '/first-animation'
    | '/pinning-elements'
    | '/scroll-trigger'
    | '/sine-easing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/back-easing'
    | '/first-animation'
    | '/pinning-elements'
    | '/scroll-trigger'
    | '/sine-easing'
    | '/'
  id:
    | '__root__'
    | '/_examples'
    | '/_examples/back-easing'
    | '/_examples/first-animation'
    | '/_examples/pinning-elements'
    | '/_examples/scroll-trigger'
    | '/_examples/sine-easing'
    | '/_examples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExamplesRouteRoute: typeof ExamplesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_examples': {
      id: '/_examples'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExamplesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_examples/': {
      id: '/_examples/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
    '/_examples/sine-easing': {
      id: '/_examples/sine-easing'
      path: '/sine-easing'
      fullPath: '/sine-easing'
      preLoaderRoute: typeof ExamplesSineEasingRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
    '/_examples/scroll-trigger': {
      id: '/_examples/scroll-trigger'
      path: '/scroll-trigger'
      fullPath: '/scroll-trigger'
      preLoaderRoute: typeof ExamplesScrollTriggerRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
    '/_examples/pinning-elements': {
      id: '/_examples/pinning-elements'
      path: '/pinning-elements'
      fullPath: '/pinning-elements'
      preLoaderRoute: typeof ExamplesPinningElementsRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
    '/_examples/first-animation': {
      id: '/_examples/first-animation'
      path: '/first-animation'
      fullPath: '/first-animation'
      preLoaderRoute: typeof ExamplesFirstAnimationRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
    '/_examples/back-easing': {
      id: '/_examples/back-easing'
      path: '/back-easing'
      fullPath: '/back-easing'
      preLoaderRoute: typeof ExamplesBackEasingRouteImport
      parentRoute: typeof ExamplesRouteRoute
    }
  }
}

interface ExamplesRouteRouteChildren {
  ExamplesBackEasingRoute: typeof ExamplesBackEasingRoute
  ExamplesFirstAnimationRoute: typeof ExamplesFirstAnimationRoute
  ExamplesPinningElementsRoute: typeof ExamplesPinningElementsRoute
  ExamplesScrollTriggerRoute: typeof ExamplesScrollTriggerRoute
  ExamplesSineEasingRoute: typeof ExamplesSineEasingRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

const ExamplesRouteRouteChildren: ExamplesRouteRouteChildren = {
  ExamplesBackEasingRoute: ExamplesBackEasingRoute,
  ExamplesFirstAnimationRoute: ExamplesFirstAnimationRoute,
  ExamplesPinningElementsRoute: ExamplesPinningElementsRoute,
  ExamplesScrollTriggerRoute: ExamplesScrollTriggerRoute,
  ExamplesSineEasingRoute: ExamplesSineEasingRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}

const ExamplesRouteRouteWithChildren = ExamplesRouteRoute._addFileChildren(
  ExamplesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ExamplesRouteRoute: ExamplesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
