/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SineEasingRouteImport } from './routes/sine-easing'
import { Route as ScrollTriggerRouteImport } from './routes/scroll-trigger'
import { Route as FirstAnimationRouteImport } from './routes/first-animation'
import { Route as BackEasingRouteImport } from './routes/back-easing'
import { Route as IndexRouteImport } from './routes/index'

const SineEasingRoute = SineEasingRouteImport.update({
  id: '/sine-easing',
  path: '/sine-easing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollTriggerRoute = ScrollTriggerRouteImport.update({
  id: '/scroll-trigger',
  path: '/scroll-trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAnimationRoute = FirstAnimationRouteImport.update({
  id: '/first-animation',
  path: '/first-animation',
  getParentRoute: () => rootRouteImport,
} as any)
const BackEasingRoute = BackEasingRouteImport.update({
  id: '/back-easing',
  path: '/back-easing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/back-easing': typeof BackEasingRoute
  '/first-animation': typeof FirstAnimationRoute
  '/scroll-trigger': typeof ScrollTriggerRoute
  '/sine-easing': typeof SineEasingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/back-easing': typeof BackEasingRoute
  '/first-animation': typeof FirstAnimationRoute
  '/scroll-trigger': typeof ScrollTriggerRoute
  '/sine-easing': typeof SineEasingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/back-easing': typeof BackEasingRoute
  '/first-animation': typeof FirstAnimationRoute
  '/scroll-trigger': typeof ScrollTriggerRoute
  '/sine-easing': typeof SineEasingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/back-easing'
    | '/first-animation'
    | '/scroll-trigger'
    | '/sine-easing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/back-easing'
    | '/first-animation'
    | '/scroll-trigger'
    | '/sine-easing'
  id:
    | '__root__'
    | '/'
    | '/back-easing'
    | '/first-animation'
    | '/scroll-trigger'
    | '/sine-easing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackEasingRoute: typeof BackEasingRoute
  FirstAnimationRoute: typeof FirstAnimationRoute
  ScrollTriggerRoute: typeof ScrollTriggerRoute
  SineEasingRoute: typeof SineEasingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sine-easing': {
      id: '/sine-easing'
      path: '/sine-easing'
      fullPath: '/sine-easing'
      preLoaderRoute: typeof SineEasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll-trigger': {
      id: '/scroll-trigger'
      path: '/scroll-trigger'
      fullPath: '/scroll-trigger'
      preLoaderRoute: typeof ScrollTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-animation': {
      id: '/first-animation'
      path: '/first-animation'
      fullPath: '/first-animation'
      preLoaderRoute: typeof FirstAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-easing': {
      id: '/back-easing'
      path: '/back-easing'
      fullPath: '/back-easing'
      preLoaderRoute: typeof BackEasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackEasingRoute: BackEasingRoute,
  FirstAnimationRoute: FirstAnimationRoute,
  ScrollTriggerRoute: ScrollTriggerRoute,
  SineEasingRoute: SineEasingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
